# Rollout: Progressive delivery với canary strategy
# Sync wave 0: Deploy trước để tạo pods
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api
  namespace: demo
  labels:
    app: api
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: ecr-registry-key
      containers:
        - name: api
          image: 730335441285.dkr.ecr.ap-southeast-1.amazonaws.com/w10:0.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: VERSION
              value: "v0.0.6"
            - name: ERROR_RATE
              value: "0"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 15
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: db-secret-volume
              mountPath: /secrets/db-secret
      volumes:
        - name: db-secret-volume
          secret:
            secretName: db-secret
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate
        startingStep: 1
      steps:
        - setWeight: 10
        - pause: { duration: 2m }
        - setWeight: 50
        - pause: { duration: 2m }
        - setWeight: 100

kubectl create secret docker-registry ecr-registry-key \
 --docker-server=730335441285.dkr.ecr.ap-southeast-1.amazonaws.com \
 --docker-username=AWS \
 --docker-password=$(aws ecr get-login-password --region ap-southeast-1) \
 --namespace=demo